minima:
  skin: dark
theme: minima
#theme: jekyll-theme-minimal
title: Resume (CV)
description: Engineering Manager helping teams and techs growing and achieving their goals.
author:
  name: hikatanguy